const constants = {
    ADD_ITEM:"ADD_ITEM",
    REMOVE_ITEM:"REMOVE_ITEM",
    GET_ITEM:"GET_ITEM",
    LIST_ITEMS:"LIST_ITEMS",
    SORT_ITEMS:"SORT_ITEMS",
    SEARCH_ITEM:"SEARCH_ITEM",
    REPLACE_CONDITION:"REPLACE_CONDITION"
}

export default constants